# air 配置文件 for user-service
root = "."

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  delay = 1000  # ms
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = true
  full_bin = ""
  include_dir = []
  include_ext = ["go"]  # 修复：移除点号
  kill_delay = "100ms"
  log = "air-build.log"  # 添加日志文件
  send_interrupt = true
  stop_on_error = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true

[misc]
  clean_on_exit = true 